/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-11-22 01:06:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.loaibean;
import bo.loaibo;
import bean.lichsubean;
import java.util.ArrayList;
import javax.websocket.Session;
import bo.giohangbo;
import dao.dangnnhapdao;

public final class lichsu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bo.loaibo");
    _jspx_imports_classes.add("javax.websocket.Session");
    _jspx_imports_classes.add("dao.dangnnhapdao");
    _jspx_imports_classes.add("bean.lichsubean");
    _jspx_imports_classes.add("bean.loaibean");
    _jspx_imports_classes.add("bo.giohangbo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Lịch sử mua hàng</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("	  <div class=\"container-fluid\">\r\n");
      out.write("	    <div class=\"navbar-header\">\r\n");
      out.write("	      <a class=\"navbar-brand\" href=\"htsachController\">Trang chủ</a>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <ul class=\"nav navbar-nav\">\r\n");
      out.write("	      <li ><a href=\"htgioController\">Giỏ hàng <b>\r\n");
      out.write("	      	");
	try {
		      		giohangbo ghbo = (giohangbo)session.getAttribute("gio");
		      		out.print(ghbo.ds.size());
	      		} catch(Exception e) {}
	      	
      out.write(" </b>\r\n");
      out.write("	      </a></li>\r\n");
      out.write("	       <li ><a href=\"thanhtoanController\">Thanh toán</a></li>\r\n");
      out.write("	       <li><a href=\"lichsuController\">Lịch sử mua hàng</a></li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("	      <li><a href=\"thoatController\"><span class=\"glyphicon glyphicon-user\">\r\n");
      out.write("	      </span> LogOut</a></li>\r\n");
      out.write("	      ");
if(session.getAttribute("dn")!=null){ 
      out.write("\r\n");
      out.write("	      <li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\">\r\n");
      out.write("	      </span> Xin chao: ");
      out.print(session.getAttribute("dn"));
      out.write("</a></li>\r\n");
      out.write("	      ");
}else{ 
      out.write("\r\n");
      out.write("	      <li><a href=\"dangnhap.jsp\"><span class=\"glyphicon glyphicon-log-in\">\r\n");
      out.write("	      </span> Login</a></li>\r\n");
      out.write("	      ");
} 
      out.write("\r\n");
      out.write("	    </ul>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<table width=\"1000\" align=\"center\">\r\n");
      out.write(" 	<tr>\r\n");
      out.write(" 		<td colspan=\"3\">\r\n");
      out.write(" 			<h1>LỊCH SỬ MUA HÀNG</h1>\r\n");
      out.write(" 		</td>\r\n");
      out.write(" 	</tr>\r\n");
      out.write(" 	\r\n");
      out.write(" 	<tr>\r\n");
      out.write(" 		<td width=\"200\" valign=\"top\">\r\n");
      out.write(" 			<table class=\"table table-hover\">\r\n");
      out.write("      	 	  ");
loaibo lbo = (loaibo) request.getAttribute("dsloai");
      	 	  	for(loaibean loai: lbo.getLoai()) {
      	 	   
      out.write("\r\n");
      out.write("      	 	     <tr>\r\n");
      out.write("      	 	        <td>\r\n");
      out.write("      	 	          <a href=\"htsachController?ml=");
      out.print(loai.getMaloai());
      out.write("\">\r\n");
      out.write("      	 	             ");
      out.print(loai.getTenloai() );
      out.write("\r\n");
      out.write("      	 	          </a>  \r\n");
      out.write("      	 	        </td>\r\n");
      out.write("      	 	      </tr>\r\n");
      out.write("      	 	      ");
} 
      out.write("\r\n");
      out.write("      	 	</table>\r\n");
      out.write(" 		</td>\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 		<td width=\"800\" valign=\"top\" >\r\n");
      out.write(" 			<table class=\"table table-hover\">\r\n");
      out.write("	 			 <tr>\r\n");
      out.write("				 	<td><b>Mã hóa đơn</b></td>\r\n");
      out.write("				    <td><b>Tên sách</b></td>\r\n");
      out.write("				    <td><b>Số lượng mua</b></td>\r\n");
      out.write("				    <td><b>Giá bán</b></td>\r\n");
      out.write("				    <td><b>Ngày mua</b></td>\r\n");
      out.write("			     </tr>\r\n");
      out.write("		      	 ");
 ArrayList<lichsubean> ls = (ArrayList<lichsubean>) request.getAttribute("ls");
		      		if(ls!=null) {
		      			for(lichsubean ds : ls) {
      out.write("\r\n");
      out.write("				      	 	<tr>\r\n");
      out.write("				      	 		<td> ");
      out.print(ds.getMaHoaDon());
      out.write(" </td>\r\n");
      out.write("					      	 	<td>\r\n");
      out.write("					      	 		<img alt=\"\" src=\"");
      out.print(ds.getAnh() );
      out.write("\" width=\"100\">\r\n");
      out.write("					      	 		");
      out.print(ds.getTensach());
      out.write("\r\n");
      out.write("					      	 	</td>\r\n");
      out.write("					      	 	<td> ");
      out.print(ds.getSoLuongMua() );
      out.write(" </td>\r\n");
      out.write("					      	 	<td> ");
      out.print(ds.getGia() );
      out.write("/cuốn </td>\r\n");
      out.write("					      	 	<td> ");
      out.print(ds.getNgayMua() );
      out.write(" </td>\r\n");
      out.write("				      	 	</tr>\r\n");
      out.write("		 			");
 }} else{ 
      out.write("\r\n");
      out.write("		 			 		<p>Lịch sử mua trống! Xin mời <a href=\"htsachController\">Mua hàng</a></p>\r\n");
      out.write("		 			");
}
      out.write("\r\n");
      out.write("	      	 </table>\r\n");
      out.write("    \r\n");
      out.write(" 		</td>\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 		<td width=\"200\" valign=\"top\" class=\"form-control\"> \r\n");
      out.write(" 			 <form action=\"htsachController\" method=\"post\">\r\n");
      out.write("				  <input class=\"form-control\" name=\"txttk\" type=\"text\" value=\"\" placeholder=\"Nhap tt\"> <br>\r\n");
      out.write("				  <input name=\"butt\" type=\"submit\" value=\"Search\" class=\"btn-primary\">\r\n");
      out.write("			</form>\r\n");
      out.write(" 		</td>\r\n");
      out.write(" 		\r\n");
      out.write(" 		\r\n");
      out.write(" 	</tr>\r\n");
      out.write(" </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
